// src/vue/src/App.vue
<script>
  import VueLogo from './assets/img/VueLogo.png';

  export default {
    data() {
      return {
        vueLogoSrc: VueLogo
      };
    }
  }
</script>

<template>
    <div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
        <h1 style="font-family: monospace;">POWERED BY EXY CLI</h1>
        <img :src="vueLogoSrc" alt="Vue" />
    </div>
</template>

<style scoped>

</style>

// src/react/src/App.jsx
import React, { Component } from 'react';

import ReactLogo from './assets/img/ReactLogo.png';
import './global.css';

export default class App extends Component {
  render() {
    return (
      <div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', flexDirection: 'column'}}>
        <h1 style={{fontFamily: 'monospace', color: 'white'}}>POWERED BY EXY CLI</h1>
        <img src={ReactLogo} alt="React" />
      </div>
    );
  }
};
